kind: stack

depends:
- freedesktop-sdk.bst:components/systemd.bst
- freedesktop-sdk.bst:components/systemd.bst
- freedesktop-sdk.bst:components/dbus.bst
- freedesktop-sdk.bst:components/pipewire.bst
- freedesktop-sdk.bst:components/wireplumber.bst
- freedesktop-sdk.bst:components/libseat.bst
- freedesktop-sdk.bst:components/polkit.bst
- freedesktop-sdk.bst:components/flatpak.bst
- freedesktop-sdk.bst:components/shadow.bst
- freedesktop-sdk.bst:components/sudo.bst
- freedesktop-sdk.bst:components/kmod.bst
- freedesktop-sdk.bst:components/linux.bst
- freedesktop-sdk.bst:extensions/mesa/mesa.bst
- freedesktop-sdk.bst:components/networkmanager.bst
- system/system-config.bst
