// Generated by generate_wrap_init.pl -- DO NOT MODIFY!

#define GLIBMM_INCLUDED_FROM_WRAP_INIT_CC
#include <glibmm.h>
#include <gdkmm/wrap_init.h>
#include <glibmm/error.h>
#include <glibmm/object.h>

// #include the widget headers so that we can call the get_type() static methods:
#include "applaunchcontext.h"
#ifndef GDKMM_DISABLE_DEPRECATED
#include "color.h"
#endif // *_DISABLE_DEPRECATED
#include "cursor.h"
#include "device.h"
#include "devicemanager.h"
#include "display.h"
#include "displaymanager.h"
#include "dragcontext.h"
#include "drawingcontext.h"
#include "event.h"
#include "frameclock.h"
#include "frametimings.h"
#include "glcontext.h"
#include "monitor.h"
#include "pixbuf.h"
#include "pixbufanimation.h"
#include "pixbufanimationiter.h"
#include "pixbufformat.h"
#include "pixbufloader.h"
#include "rectangle.h"
#include "rgba.h"
#include "screen.h"
#include "seat.h"
#include "timecoord.h"
#include "types.h"
#include "visual.h"
#include "window.h"

#if defined(__GNUC__) || defined (__clang__)
// gcc or clang, https://gitlab.gnome.org/GNOME/glibmm/-/issues/119
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Winconsistent-dllimport"
#elif defined(_MSC_VER)
#pragma warning( push )
#pragma warning( disable : 4273 ) // Disable MSVC warning C4273 in wrap_init.cc momentarily
#endif

extern "C"
{
//Declarations of the *_get_type() functions:

GType gdk_app_launch_context_get_type(void);
GType gdk_cursor_get_type(void);
GType gdk_device_get_type(void);
GType gdk_device_manager_get_type(void);
GType gdk_display_get_type(void);
GType gdk_display_manager_get_type(void);
GType gdk_drag_context_get_type(void);
GType gdk_drawing_context_get_type(void);
GType gdk_frame_clock_get_type(void);
GType gdk_gl_context_get_type(void);
GType gdk_monitor_get_type(void);
GType gdk_pixbuf_get_type(void);
GType gdk_pixbuf_animation_get_type(void);
GType gdk_pixbuf_animation_iter_get_type(void);
GType gdk_pixbuf_loader_get_type(void);
GType gdk_screen_get_type(void);
GType gdk_seat_get_type(void);
GType gdk_visual_get_type(void);
GType gdk_window_get_type(void);

//Declarations of the *_error_quark() functions:

GQuark gdk_gl_error_quark(void);
GQuark gdk_pixbuf_error_quark(void);
} // extern "C"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#pragma warning( pop )
#endif

namespace Gdk {

//Declarations of the *_Class::wrap_new() methods, instead of including all the private headers:

class AppLaunchContext_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Cursor_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Device_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class DeviceManager_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Display_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class DisplayManager_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class DragContext_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class DrawingContext_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class FrameClock_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class GLContext_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Monitor_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Pixbuf_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class PixbufAnimation_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class PixbufAnimationIter_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class PixbufLoader_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Screen_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Seat_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Visual_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };
class Window_Class { public: static Glib::ObjectBase* wrap_new(GObject*); };

void wrap_init()
{
  // Register Error domains in the main namespace:
  Glib::Error::register_domain(gdk_gl_error_quark(), &GLError::throw_func);
  Glib::Error::register_domain(gdk_pixbuf_error_quark(), &PixbufError::throw_func);

  // Map gtypes to gtkmm wrapper-creation functions:
  Glib::wrap_register(gdk_app_launch_context_get_type(), &AppLaunchContext_Class::wrap_new);
  Glib::wrap_register(gdk_cursor_get_type(), &Cursor_Class::wrap_new);
  Glib::wrap_register(gdk_device_get_type(), &Device_Class::wrap_new);
  Glib::wrap_register(gdk_device_manager_get_type(), &DeviceManager_Class::wrap_new);
  Glib::wrap_register(gdk_display_get_type(), &Display_Class::wrap_new);
  Glib::wrap_register(gdk_display_manager_get_type(), &DisplayManager_Class::wrap_new);
  Glib::wrap_register(gdk_drag_context_get_type(), &DragContext_Class::wrap_new);
  Glib::wrap_register(gdk_drawing_context_get_type(), &DrawingContext_Class::wrap_new);
  Glib::wrap_register(gdk_frame_clock_get_type(), &FrameClock_Class::wrap_new);
  Glib::wrap_register(gdk_gl_context_get_type(), &GLContext_Class::wrap_new);
  Glib::wrap_register(gdk_monitor_get_type(), &Monitor_Class::wrap_new);
  Glib::wrap_register(gdk_pixbuf_get_type(), &Pixbuf_Class::wrap_new);
  Glib::wrap_register(gdk_pixbuf_animation_get_type(), &PixbufAnimation_Class::wrap_new);
  Glib::wrap_register(gdk_pixbuf_animation_iter_get_type(), &PixbufAnimationIter_Class::wrap_new);
  Glib::wrap_register(gdk_pixbuf_loader_get_type(), &PixbufLoader_Class::wrap_new);
  Glib::wrap_register(gdk_screen_get_type(), &Screen_Class::wrap_new);
  Glib::wrap_register(gdk_seat_get_type(), &Seat_Class::wrap_new);
  Glib::wrap_register(gdk_visual_get_type(), &Visual_Class::wrap_new);
  Glib::wrap_register(gdk_window_get_type(), &Window_Class::wrap_new);

  // Register the gtkmm gtypes:
  g_type_ensure(AppLaunchContext::get_type());
  g_type_ensure(Cursor::get_type());
  g_type_ensure(Device::get_type());
  g_type_ensure(DeviceManager::get_type());
  g_type_ensure(Display::get_type());
  g_type_ensure(DisplayManager::get_type());
  g_type_ensure(DragContext::get_type());
  g_type_ensure(DrawingContext::get_type());
  g_type_ensure(FrameClock::get_type());
  g_type_ensure(GLContext::get_type());
  g_type_ensure(Monitor::get_type());
  g_type_ensure(Pixbuf::get_type());
  g_type_ensure(PixbufAnimation::get_type());
  g_type_ensure(PixbufAnimationIter::get_type());
  g_type_ensure(PixbufLoader::get_type());
  g_type_ensure(Screen::get_type());
  g_type_ensure(Seat::get_type());
  g_type_ensure(Visual::get_type());
  g_type_ensure(Window::get_type());

} // wrap_init()

} // Gdk

